<tool name="py3-flawfinder" version="2.0.19-7f09b7e417d52b8dd618c1005aeeb78b">
  <client>
    <environment name="PY3_FLAWFINDER_BASE" default="/cvmfs/cms.cern.ch/el9_amd64_gcc11/external/py3-flawfinder/2.0.19-7f09b7e417d52b8dd618c1005aeeb78b"/>
  </client>
  <runtime name="PATH" value="$PY3_FLAWFINDER_BASE/bin" type="path"/>
</tool>
